Feature: Bowling
  In order to ...
  As ...
  I want to ...

  Background:
    Given ...

  Scenario: I never knock down pin
    When all of my balls are landing in the gutter
    Then my score should be 0
