Feature: Bowling
  In order to ...
  As ...
  I want to ...

  Scenario: I never knock down pin
    Given a new bowling game
    When all of my balls are landing in the gutter
    Then my score should be 0
